<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<html lang="en">
<head>
<title>24MAGIC — XML Sitemap</title>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="robots" content="noindex" />
<style>
  :root {
    --bg: #fff8f8;
    --card: #ffffff;
    --border: #dfbfc3;
    --text: #1f1a1b;
    --muted: #584145;
    --accent: #830036;
    --accent2: #a61d4c;
  }
  * { box-sizing: border-box; }
  body {
    margin: 0;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    background: var(--bg);
    color: var(--text);
    padding: 40px 20px 80px;
  }
  .wrap { max-width: 960px; margin: 0 auto; }
  header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    flex-wrap: wrap;
    gap: 12px;
    margin-bottom: 28px;
  }
  h1 {
    font-size: 22px;
    font-weight: 800;
    margin: 0;
    color: var(--accent);
  }
  .badge {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    font-size: 12px;
    font-weight: 700;
    letter-spacing: 0.03em;
    text-transform: uppercase;
    background: rgba(166, 29, 76, 0.1);
    color: var(--accent);
    padding: 6px 12px;
    border-radius: 999px;
  }
  .summary {
    font-size: 14px;
    color: var(--muted);
    margin-bottom: 20px;
  }
  .card {
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 16px;
    overflow: hidden;
    box-shadow: 0 1px 3px rgba(31, 26, 27, 0.06);
  }
  table {
    width: 100%;
    border-collapse: collapse;
    font-size: 14px;
  }
  thead th {
    text-align: left;
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    color: var(--muted);
    padding: 14px 18px;
    border-bottom: 1px solid var(--border);
    background: #fbf1f2;
  }
  tbody td {
    padding: 14px 18px;
    border-bottom: 1px solid #f0dfe1;
    vertical-align: middle;
  }
  tbody tr:last-child td { border-bottom: none; }
  tbody tr:hover { background: #fff8f8; }
  a.loc {
    color: var(--accent);
    text-decoration: none;
    font-weight: 600;
    word-break: break-all;
  }
  a.loc:hover { text-decoration: underline; }
  .priority-pill {
    display: inline-block;
    min-width: 40px;
    text-align: center;
    font-weight: 700;
    font-size: 12px;
    padding: 3px 8px;
    border-radius: 999px;
    background: rgba(255, 181, 91, 0.25);
    color: #8a5b12;
  }
  .muted { color: var(--muted); }
  footer {
    margin-top: 24px;
    font-size: 12px;
    color: var(--muted);
    text-align: center;
  }
</style>
</head>
<body>
<div class="wrap">
  <header>
    <h1>24MAGIC — XML Sitemap</h1>
    <span class="badge">
      <xsl:value-of select="count(sitemap:urlset/sitemap:url)" /> URLs
    </span>
  </header>
  <p class="summary">
    This is a human-readable view of <code>sitemap.xml</code>, generated for search engines like Google.
    Submit the raw file at <a class="loc" href="/sitemap.xml">/sitemap.xml</a> in Google Search Console.
  </p>
  <div class="card">
    <table>
      <thead>
        <tr>
          <th>URL</th>
          <th>Last Modified</th>
          <th>Change Frequency</th>
          <th>Priority</th>
        </tr>
      </thead>
      <tbody>
        <xsl:for-each select="sitemap:urlset/sitemap:url">
          <tr>
            <td>
              <a class="loc">
                <xsl:attribute name="href"><xsl:value-of select="sitemap:loc" /></xsl:attribute>
                <xsl:value-of select="sitemap:loc" />
              </a>
            </td>
            <td class="muted"><xsl:value-of select="substring(sitemap:lastmod, 1, 10)" /></td>
            <td class="muted"><xsl:value-of select="sitemap:changefreq" /></td>
            <td><span class="priority-pill"><xsl:value-of select="sitemap:priority" /></span></td>
          </tr>
        </xsl:for-each>
      </tbody>
    </table>
  </div>
  <footer>Generated by 24MAGIC · <xsl:value-of select="count(sitemap:urlset/sitemap:url)" /> routes indexed</footer>
</div>
</body>
</html>
</xsl:template>
</xsl:stylesheet>
